# Site settings
title: dario.com • Security • Privacy
email: contact@dario.com
description: Understand - Take Action. Security is a business requirement. Protecting privacy is good business.
author: dario
url: https://dario.com
baseurl: ''
logo: "/img/chklst.png"
twitter_username: darioS3C
telephone_number: +1-514-572-0424
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
