# Site settings
title: dario.com • Security • Privacy
description: Security is a business requirement. Protecting privacy is good business. Protect your data and business. dario.com
author: dario.com
url: https://dario.com
english_url: https://dario.com
french_url: https://dario.site
baseurl: ''
resources_url: 'resources'
logo: "/img/chklst.png"
email: contact@dario.com
twitter_username: darioS3C
telephone_number:
copyright: dario.com • Security • Privacy
# Google Analytics • To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-98131817-2
# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
